version: '3.4'
services:
  lighthouse-prater.avado.dnp.dappnode.eth:
    image: 'lighthouse-prater.avado.dnp.dappnode.eth:0.0.4'
    build:
      context: ./build
      args:
        VERSION: v4.6.0
    volumes:
      - 'data:/data'
    ports:
      - '9003:9003'
      - '9003:9003/udp'
      - '9999:9999'
    environment:
      - EXTRA_OPTS_BEACON_NODE=
      - EXTRA_OPTS_VALIDATOR_CLIENT=
volumes:
  data: {}
