name: Release
on:
  push:
    branches:
      - master
      - main
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: AvadoDServer/ci-release-action@node16
        with:
          rpcToken: ${{ secrets.RPC_TOKEN }}
